Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import sys
>>> n1, n2 = sys.stdin.readline().rstrip().split()
472
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    n1, n2 = sys.stdin.readline().rstrip().split()
KeyboardInterrupt
>>> 'abc'.split()
['abc']
>>> a = 'abc'
>>> a[0]
'a'
>>> 
= RESTART: C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.1/2588.py
472
Traceback (most recent call last):
  File "C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.1/2588.py", line 3, in <module>
    n1 = int(sys.stdin.readline().rstrip().split())
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
>>> 
= RESTART: C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.1/2588.py
472
385
Traceback (most recent call last):
  File "C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.1/2588.py", line 5, in <module>
    a, b, c = map(int, (n2[0], n2[1], n2[2]))
IndexError: list index out of range
>>> 
= RESTART: C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.1/2588.py
472
385
1416
3776
2360
7552
>>> 
= RESTART: C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.1/2588.py
472
385
2360
3776
1416
181720
>>> 
= RESTART: C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.2/2753.py
2012
1
>>> 
= RESTART: C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.2/2753.py
2000
0
>>> 
= RESTART: C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.2/2753.py
2000
1
>>> 
= RESTART: C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.2/14681.py
1
1
1
>>> 
= RESTART: C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.2/14681.py
1
-4
4
>>> 
= RESTART: C:/Users/Ji Eui Hong/AppData/Local/Programs/Python/Python38/2739.py =
= RESTART: C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.2/2753.py
Traceback (most recent call last):
  File "C:/Users/Ji Eui Hong/AppData/Local/Programs/Python/Python38/2739.py", line 3, in <module>
    n = int(sys.stdin.readline())
ValueError: invalid literal for int() with base 10: '= RESTART: C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.2/2753.py\n'
>>> 
= RESTART: C:/Users/Ji Eui Hong/AppData/Local/Programs/Python/Python38/2739.py =
5
Traceback (most recent call last):
  File "C:/Users/Ji Eui Hong/AppData/Local/Programs/Python/Python38/2739.py", line 6, in <module>
    printf("{n} * {i} = {n*i}")
NameError: name 'printf' is not defined
>>> 
= RESTART: C:/Users/Ji Eui Hong/AppData/Local/Programs/Python/Python38/2739.py =
5
5 * 0 = 0
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
>>> 
= RESTART: C:/Users/Ji Eui Hong/AppData/Local/Programs/Python/Python38/2739.py =
4
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
>>> 
= RESTART: C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.3/10950.py
Traceback (most recent call last):
  File "C:/Users/Ji Eui Hong/Documents/Self study/Algorithms/Baekjoon/단계별/lv.3/10950.py", line 3, in <module>
    n = int(sys.stdin.readline())
KeyboardInterrupt
>>> 
= RESTART: C:/Users/Ji Eui Hong/AppData/Local/Programs/Python/Python38/15552.py
Traceback (most recent call last):
  File "C:/Users/Ji Eui Hong/AppData/Local/Programs/Python/Python38/15552.py", line 1, in <module>
    n = int(sys.stdin.readline())
NameError: name 'sys' is not defined
>>> 
= RESTART: C:/Users/Ji Eui Hong/AppData/Local/Programs/Python/Python38/15552.py
5
1 1
2
12 34
46
5 500
505
40 60
100
1000 1000
2000
>>> 